### ISSUE TITLE
[Question] Why the upper bound of the selective risk is non-monotonic in the tutorial of selective classification?

### ISSUE THREAD

**Issue by isabellacama** [aangelopoulos/conformal-prediction#12]
While trying to understand the method for selective classification, I tried to run your code and to plot the curves of the selective risk and its upper bound.
This is the code that I added to plot these curves:

```
selective_risk_values = np.array([selective_risk(lam) for lam in lambdas])
selective_risk_values_ub = np.array([selective_risk_ub(lam) for lam in lambdas])
plt.plot(lambdas, selective_risk_values, label='Selective Risk')
plt.plot(lambdas, selective_risk_values_ub, label='Selective Risk upper bound')
plt.axhline(y=alpha, color='red', linestyle='--', label='alpha')
plt.legend()
```

I was expecting to see the upper bound to be monotonic and descending, but as you can see in the image below, it is not.

From the paper "Gentle introduction to conformal prediction", I assumed that the upper bound should be monotonic because it was introduced to overcome the issue related to the fact that the selective risk is non monotonic (section 5.5 Selective classification).

<img width="555" alt="Screenshot 2024-01-19 alle 19 00 34" src="https://github.com/aangelopoulos/conformal-prediction/assets/92362917/83d3e0e7-1175-4c20-bb2c-10bb030a6193">

When testing it with my own dataset, I get an extreme example of this behaviour.

![selective_risk](https://github.com/aangelopoulos/conformal-prediction/assets/92362917/069fedf4-2290-4e2b-84f8-e516c606c76b)

Is this an expected behaviour or the assumption of the upper bound being monotonic is wrong?

Thank you!

**Comment by aangelopoulos** [comment]
Really great quesion!

The selective risk is _not_ monotone, and neither is the upper-bound!

Nonetheless, we can come up with techniques for dealing with non-monotone risks too, and this is what we use: see https://arxiv.org/abs/2110.01052 for the paper on this topic, and specifically Section 3.2 :)

Angelopoulos, A. N., Bates, S., Candès, E. J., Jordan, M. I., & Lei, L. (2021). Learn then test: Calibrating predictive algorithms to achieve risk control. arXiv preprint arXiv:2110.01052.

**Comment by isabellacama** [comment]
Hello,

thank you for your prompt response!

I have some additional questions and I would appreciate your input.

The upper bound doesn't have to be monotone then. In the case of selective accuracy I understand that it can be controlled by choosing $\hat{\lambda}$ properly (definition of $\hat{\lambda}$ right before Proposition 4 of section 5.5 Selective classification). More specifically, I understand that the upper bound is controlled by $\alpha$ $\forall \lambda \geq \hat{\lambda}$. In my case this condition is trivially satisfied, meaning that the selected $\hat{\lambda}$ is the most extreme one, because the upper bound results to be always higher than the selected $\alpha$.

I attach other examples that I get on my dataset by setting $\alpha = 0.05$, `nlambda(lam) >= 1, 10, 30`, respectively, from top to bottom. My calibration set size is around 250 samples.

![selective_risk_alpha005_nlambda1](https://github.com/aangelopoulos/conformal-prediction/assets/92362917/03caf6b9-a1ef-4ac8-945b-062c1dcd67b0)
![selective_risk_alpha005_nlambda10](https://github.com/aangelopoulos/conformal-prediction/assets/92362917/8ca6ebbd-c5d5-41c7-a24c-93ede1f34635)
![selective_risk_alpha005_nlambda30](https://github.com/aangelopoulos/conformal-prediction/assets/92362917/7b3b2cc1-016e-4501-91a2-2cc7ca6414d1)


First I would like to ask you how does the parameters 1, 10, 30 affect the upper bound? Why do you set `nlambda(lam) >= 30` in your code?

Also, why do you think I always obtain an upper bound which is that much higher than the selective risk, and also always higher than $\alpha$? In this case the $\hat{\lambda}$ is always the biggest possible among the selected lambdas.

For a binary classification problem, what calibration set size should be used in order to obtain meaningful results?

Thank you again!
Isabella

**Comment by aangelopoulos** [comment]
Hey Isabella!

  Yeah, the n >= 30 is a little bit of a hack. Basically, you need to find a good starting point to do the search through `\lambda`-space.  Setting n higher may make you less conservative, but it's a little bit hacky.

  The results for selective classification tend to be quite conservative, since it's a non-monotone risk, and we use the LTT procedure.  Depending on the problem setup, say that you need about 1K+ data points to make this non-conservative. If you have fewer data points, the concentration bound can be loose, which is why you see the selective risk higher than alpha!

Hope this helps :)
Best,
Anastasios

**Comment by aangelopoulos** [comment]
Stale, avoiding bot comments. Reopen or DM if you like @isabellacama !
