### ISSUE TITLE
`np.quantile`: deprecated `interpolation` argument

### ISSUE THREAD

**Issue by vincentarelbundock** [aangelopoulos/conformal-prediction#2]
Thanks a lot for writing this very interesting paper and for publishing the notebooks.

FYI, the `interpolation` argument appears to be deprecated in recent versions of `numpy.quantile`:

https://numpy.org/devdocs/reference/generated/numpy.quantile.html

**Comment by aangelopoulos** [comment]
Thank you, Vincent!
I kept the `interpolation` argument for backwards-compatibility, but in the future might remove it.  
Did you get an error or just a warning when you ran the code?

**Comment by vincentarelbundock** [comment]
Oh no, not at. I just happened to click on the help file while I was running your notebooks and noticed this.

Will close since you are aware.

Thanks again for the public goods!

**Comment by aangelopoulos** [comment]
My pleasure, thank you Vincent!!
