### ISSUE TITLE
colab weather example won't run

### ISSUE THREAD

**Issue by microprediction** [aangelopoulos/conformal-prediction#4]
Requires an external file. Maybe change to load it remotely from the repo so colab just works?

**Comment by aangelopoulos** [comment]
This is super strange.  I also can't get it to download the data.  I'll look into this.

**Comment by aangelopoulos** [comment]
Turns out there was an update to colab that causes `gdown` to break.  I'll fix it by forcing a different gdown installation.

`!pip install -U --no-cache-dir gdown --pre`

**Comment by aangelopoulos** [comment]
Should be fixed by #5

**Comment by microprediction** [comment]
thxnks!
