### ISSUE TITLE
Predictive uncertainty in weather-time-series-distribution-shift notebook

### ISSUE THREAD

**Issue by CheeGY** [aangelopoulos/conformal-prediction#7]
First of all, I would like to thank all contributors to this repository. Appreciate the great work that goes behind creating and maintaining this repository.

I was looking through the notebook, [weather-time-series-distribution-shift.ipynb](https://github.com/aangelopoulos/conformal-prediction/blob/main/notebooks/weather-time-series-distribution-shift.ipynb), and notice that in the last 4 lines of the second section, we have: 
`sort_idx = np.argsort(times)`
`pred_mean = pred_mean[sort_idx]`
`temperatures = temperatures[sort_idx]`
`times = times[sort_idx]`

Should the sorting also be done for the uncertainty data, _i.e._, by adding the line `pred_uncertainty=pred_uncertainty[sort_idx]`?

**Comment by aangelopoulos** [comment]
Nice catch, thanks so much!

**Comment by aangelopoulos** [comment]
Fixed in commit `dc506f8e1b0e597021603bb702a2fb190b5ab4fd`
